[web]
  title = "Blue Rose Nails and Beauty"
  port = 8910
  apiUrl = "/api"
  includeEnvironmentVariables = []
[api]
  port = 8911
[browser]
  open = true
[notifications]
  versionUpdates = ["latest"]
